LJ/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using System.Threading.Tasks;

using System.Data.Entity;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity.ModelConfiguration.Conventions;
using LJ.Repository.BlogRepository;
using LJ.Models.Blog;
using LJ.Models.User;
using LJ.ViewModels;
using LJ.ViewModels.User;
using LJ.ViewModels.Blog;
using System.IO;
using LJ.Filters;
using LJ.Models.Visitor;
using Microsoft.AspNet.Identity.Owin;





namespace LJ.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
      
        private const int userPostsPerPage = 10;// posts per page for user
        private const int topPostsPerPage = 10; // top posts per page
        private IBlogRepository<Post,int> _blogRepository;
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        //==============================================
        public BlogController(IBlogRepository<Post,int> blogRepository)
        {
            _blogRepository = blogRepository;
           

        }

        //==============================================
        public BlogController(IBlogRepository<Post, int> blogRepository, ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            _blogRepository = blogRepository;
            UserManager = userManager;
            SignInManager = signInManager;

        }

        private async Task<ApplicationUser> GetCurrentUserAsync()
        {
            return await UserManager.FindByIdAsync(User.Identity.GetUserId());
        }



        //==============================================
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        //==============================================
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        //==============================================
        public ActionResult Index()
        {
            IEnumerable<Post> posts = _blogRepository.GetAll(1,10);
            return View(posts);
        }

        
       

        
        //==============================================
        public ActionResult GetPostsOLd(int post = 1, int perPage = 10)
        {
            ModelViewPosts mv = new ModelViewPosts();

            mv.Posts = _blogRepository.GetAll(post, perPage);
            mv.TotalPosts = _blogRepository.TotalPosts();
            ViewBag.Title = "Top Posts";
            return View("Posts", mv);
        }

        
       
        //================================================
        [ChildActionOnly]
        public ActionResult Comments(PostViewModel model, string sortOrder)
        {
        return PartialView(model);
        }


      // for View
        //====================================================
        public PartialViewResult ChildReplies(int parentReplyId, int level)
        {
            ViewBag.level = level;
            IEnumerable<CommentViewModel> v = _blogRepository.GetChildReplies(parentReplyId);
                return PartialView("ChildReplies", v);
        }


        
        // Like and dislake post, comment, reply
        //=============================================
        public int LikeDislikeCount(int typeAndlike, int id)
        {       
            return _blogRepository.LikeDislikeCount(typeAndlike, id);                 
        }



        //==============================================
        [AcceptVerbs(HttpVerbs.Post)]
        //[VisitorActionFilter(ActionType = (int)ActionType.SeeBlog)]
        public JsonResult UpdateLikes(int id, string username, int likeordislike, string sortorder="")
        {
            string name = User.Identity.GetUserName();
            int count = _blogRepository.UpdateLikes(id, name, likeordislike);
            return Json(new { count = count }, JsonRequestBehavior.AllowGet);
        }


        //==============================================
        [AcceptVerbs(HttpVerbs.Post)]
       // [VisitorActionFilter(ActionType = (int)ActionType.SeeBlog)]
        public JsonResult GetLikesList(int id, string username, int likeordislike, int numbertoshow)
        {
            var allUserNames = _blogRepository.GetListLikes(id, likeordislike);
            var allUserNamesCount = allUserNames.Count();            
            return Json(
                        new { count = allUserNamesCount,
                              usernames = allUserNames.Take(numbertoshow),
                              likeordislike = Enum.GetName(typeof(Likes), likeordislike & ((int)Likes.LikeDislike))
                        },
                        JsonRequestBehavior.AllowGet);
        }  
    



        // Add new comment repoly
        //======================================
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
      //[VisitorActionFilter(ActionType = (int)ActionType.SeeBlog, PostId = "postid")]
        public ActionResult NewParentReply(string body, string comusername, int postid, int id, string slug, int userimageid)
        {
            var reply = new Reply()
            {
                Id = 0,
                UserImageId = userimageid,
                PostId = postid,
                CommentId = id,
                ParentReplyId = null,
                DateTime = DateTime.Now,
                UserName = comusername,
                Body = body,
            };
            int newId =  _blogRepository.AddNewReply(reply);
            //return Json(new { id = newId }, JsonRequestBehavior.AllowGet);
            return RedirectToAction("GetUserPost", new { id = postid });       
        }

        //=========================================
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)] //string preplyid, string comUserName, string replyBody)
      //  [VisitorActionFilter(ActionType = (int)ActionType.SeeBlog)]
       public ActionResult NewChildReply(string body, string comusername, int id, int userimageid)
        {
            Reply reply = _blogRepository.GetReplyById(id);
            var newReply = new Reply()
            {
                Id = 0,
                UserImageId = userimageid,
                PostId = reply.PostId,
                CommentId = reply.CommentId,
                ParentReplyId =id,
                DateTime = DateTime.Now,
                UserName = comusername,
                Body = body,
            };
            int newId = _blogRepository.AddNewReply(newReply);
            return RedirectToAction("GetUserPost", new { id = reply.PostId });
        }

        //==============================================
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
      //  [VisitorActionFilter(ActionType = (int)ActionType.SeeBlog, PostId = "id")]
        public ActionResult NewComment(string body, string comusername, int id, int userimageid, string slug)
        {            
            Comment newComment = new Comment()
            {
                Id = 0,
                UserImageId = userimageid,
                PostId = id,
                DateTime = DateTime.Now,
                UserName = comusername,
                Body = body,
            };
            int newId = _blogRepository.AddNewComment(newComment);
            return RedirectToAction("GetUserPost", new { id = newComment.PostId });
        }



        // Delete comment repky
       [AcceptVerbs(HttpVerbs.Post)]
      // [VisitorActionFilter]
       public JsonResult DeleteComment(int commentid, string username)
       {
           var deleteInfo = _blogRepository.DeleteComment(commentid, username);
           deleteInfo.DeletedReplyText = "";
           return Json(deleteInfo, JsonRequestBehavior.AllowGet);
       }

       //==============================================
       [AcceptVerbs(HttpVerbs.Post)]
      // [VisitorActionFilter]
       public JsonResult DeleteReply(int replyid, string username)
       {
           var deleteInfo = _blogRepository.DeleteReply(replyid, username);        
           return Json(deleteInfo, JsonRequestBehavior.AllowGet);
       }

       //==============================================
       [HttpPost]
       //[VisitorActionFilter(PostId = "postid")]
       public  ActionResult DeletePost(int postid, int nextid, int previd, string username)
       {
           var deleteInfo = _blogRepository.DeletePost(postid, username);
           if (nextid == 0 && previd == 0)
               return RedirectToAction("GetUserPosts", new { id = username });
           else if (nextid == 0 || previd == 0) 
               return RedirectToAction("GetUserPost", new { id = previd +nextid});
            else 
               return RedirectToAction("GetUserPost", new { id = nextid});
       }



       //==============================================
       [HttpPost]
      // [ValidateAntiForgeryToken]
       [ValidateInput(false)]
      // [VisitorActionFilter]
       public async Task<ActionResult> EditComment(int id, string body, string comusername, int userimageid)
       {
           var user = await GetCurrentUserAsync();
           // if (comusername == user.UserName)

          
           int postId = _blogRepository.EditComment(id, body, comusername, userimageid);

LJ/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LJ.Repository.BlogRepository;
using LJ.Models.Blog;
using LJ.Models.User;
using LJ.ViewModels.User;
using LJ.ViewModels;
using LJ.Filters;
using LJ.Models.Visitor;

namespace LJ.Controllers
{
    public class HomeController : Controller
    {
         private IBlogRepository<Post,int> _blogRepository;
         private static int UsersPerPage = 20;
         
         public HomeController(IBlogRepository<Post, int> blogRepository)
        {
            _blogRepository = blogRepository;
           

        }
         [VisitorActionFilter(ActionType = (int)ActionType.SeeWebsite)]
        public ActionResult Index()
        {
            return View();
        }

       [VisitorActionFilter(ActionType = (int)ActionType.SeeWebsite)]
        public ActionResult Help()
        {
            return View();
        }

        [VisitorActionFilter(ActionType = (int)ActionType.SeeWebsite)]
        public ActionResult About()
        {
            ViewBag.Message = "About";

            return View();
        }

         [VisitorActionFilter(ActionType = (int)ActionType.SeeWebsite)]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        
    }
}

LJ/Views/Home/About.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDemo.cshtml";
}

@{
    ViewBag.Title = "About Page";
}

@section MainContent{

<div class="row">
    <div class="  col-xs-12 text-left">
        <ol id="About" class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
            <li class="active">About</li>
        </ol>
    </div>

    <div class="  col-xs-12 text-left">
        <p>
            <b>Blogging website</b> with functionality similar to <a href="https://en.wikipedia.org/wiki/LiveJournal">"LiveJournal"</a>,
             where each user has a blog, friends list and profile. 
             Posts and blogs ratings for  top lines are calculated every @LJ.Controllers.VisitorController.JOB_INTERVAL_RATING hours as a background job.
             Statistics reports are available at website and blog levels.<br/> Demo logins  at <a href="/Home/Help">"Help"</a>.
        </p>
    </div>
 </div>

    <div class="row" style="margin-top:70px;" >
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li><a href="#About">About</a></li>
                <li class="active">Website terms and icons</li>
            </ol>
        </div>
    
        <div class="  col-xs-12 text-left">

            <dl>
                <dt>Blog</dt>
                <dd>-  user posts with the comments left by other users</dd>
                <dt>Profile</dt>
                <dd>- information about user, statistics</dd>
                <dd>- tool to crop  images for userpics</dd>
                <dt>Friends line</dt>
                <dd>- the most recent blog posts of the people on user's friends list</dd>
                <dt> Friends list</dt>
                <dd>- used to show entries on user Friends Line and restrict access to his/her posts</dd>
                <dt> Friends groups</dt>
                <dd>- used to filter user Friends Line and restrict access to his/her posts</dd>


                <dt>Relationships</dt>
                <dd>
                    -  <span class="glyphicon glyphicon-arrow-left" aria-hidden="true" style="color:#0d47a1;"></span>
                    <span aria-hidden="true" class="glyphicon glyphicon-arrow-right" style="color:lightgray;"></span>
                    friend, user added another user to his/her friends list
                </dd>
                <dd>
                    -  <span class="glyphicon glyphicon-arrow-left" aria-hidden="true" style="color:lightgray;"></span>
                    <span aria-hidden="true" class="glyphicon glyphicon-arrow-right" style="color:green;"></span>
                    friend of, user added by another user to his/her friends list
                </dd>
                <dd>
                    -  <span class="glyphicon glyphicon-arrow-left" aria-hidden="true" style="color:#0d47a1;"></span>
                    <span aria-hidden="true" class="glyphicon glyphicon-arrow-right" style="color:green;"></span>
                    mutual friend, user is both a friend and a friend of
                </dd>

                <dt> Security levels</dt>
                <dd>- <span class="glyphicon glyphicon-none demo-icons"></span> public (user posts are public)</dd>
                <dd>- <span class="glyphicon glyphicon-eye-open demo-icons"></span> friends  (user posts can see only his/her friends)</dd>
                <dd>- <span class="glyphicon glyphicon-eye-close demo-icons"> </span> custom groups (user posts can see only groups of his/her friends) </dd>
                <dd>- <span class="glyphicon glyphicon-lock demo-icons"> </span> private ( only user)</dd>


                <dt>Top Posts</dt>
                <dd>- the most recent popular public posts</dd>
                <dd>- top  post ratings calculated by post  visitors, received comments, likes, dislikes</dd>

                <dt>Top Bloggers</dt>
                <dd>- users whose posts are popular
                <dd>- top blog  ratings calculated by  blog visitors, friends, received comments, likes, dislikes </dd>
                <dd>
                    - arrows indicate changes in user top rating:
                    some changes - <span class="glyphicon glyphicon-arrow-up" aria-hidden="true" style="color:green"></span> 5,
                    <span aria-hidden="true" class="glyphicon glyphicon-arrow-down" style="color:gray;"></span> 8,
                    no changes - <span class="glyphicon glyphicon-arrow-up" aria-hidden="true" style="color:green"></span><span aria-hidden="true" class="glyphicon glyphicon-arrow-down" style="color:gray;"></span>
                </dd>

                <dt>Administrator</dt>
                <dd>- manage background jobs (<span style="font-weight:bolder;font-size:16px;color:gray;">Σ</span> top ratings, <span class="glyphicon glyphicon-stats" style="color:gray;"></span> top positions, visitor logs, history)</dd>
                <dd>- manage post filters: tags and categories </dd>
                
                
                <dt>Analytics</dt>
                <dd>- used custom analytics not google analytics</dd>

                <dt class="about-analytics">Website Analytics</dt>
                <dd class="about-analytics">- by online and history visitors</dd>
                <dd class="about-analytics">- posts and blogs ratings charts</dd>
                <dd class="about-analytics">- posts and blogs top lines</dd>

                <dt class="about-analytics">Admin Analytics</dt>
                <dd class="about-analytics">- by time  spent on pages, bounce and exit pages </dd>
                <dd class="about-analytics">- by   information about visitors</dd>

                <dt class="about-analytics">Blog Analytics</dt>
                <dd class="about-analytics">- by blog  ratings</dd>
                <dd class="about-analytics">- by posts  (received comments, likes, dislikes)</dd>
                <dd class="about-analytics">- by comments (received and posted)</dd>
                <dd class="about-analytics">
                    - by user and user friends actions (
                    <span class="glyphicon glyphicon-plus" aria-hidden="true" style="color:gray"></span>
                    <span class="glyphicon glyphicon-minus" aria-hidden="true" style="color:gray;"></span>
                    from friends lists)
                </dd>
                <dd class="about-analytics">- by visitors (time spent on pages, bounce and exit pages)</dd>

                <dt>Background Jobs</dt>
                <dd>- blog  and  posts  ratings calculated every @LJ.Controllers.VisitorController.JOB_INTERVAL_RATING hours </dd>
                <dd>- visitors history calculated  every 24 hours</dd>
                <dd>- page hits saved on every request</dd>
               
            </dl>
        </div>
    </div>

    <div class="row" style="margin-top:80px;" id="Software">
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li><a href="#About">About</a></li>
                <li class="active">Used software</li>
            </ol>
        </div>

        <div class="  col-xs-12 text-left">
            <dl>
                <dt>Languages</dt>
                <dd>- C#, JavaScript</dd>
                <dt>Database</dt>
                <dd>- MS SQL Server 2014</dd>
                <dt>ORM</dt>
                <dd>- Entity Framework 6 (Code First)</dd>
                <dt>Background processing</dt>
                <dd>- <a href="http://hangfire.io/">Hangfire</a></dd>
                <dt>Internet</dt>
                <dd>-  ASP.NET MVC 4, JavaScript, jQuery, CSS</dd> 
                <dt>Responsive web design</dt>
                <dd> - front-end web framework - Bootstrap 3</dd>

                <dt>Plugins</dt> 
                <dd> - <a href="https://www.tinymce.com">tinyMCE</a>,  advanced HTML editor</dd>
                <dd> - <a href="http://odyniec.net/projects/imgareaselect">imgAreaSelect</a>, an image cropping tool</dd>
                <dd> - <a href="http://designwithpc.com/Plugins/ddSlick">ddSlick</a>,  a custom drop down with images</dd>
                <dd> - <a href="http://www.highcharts.com/demo">highCharts</a>,  a charting library</dd>
                <dd> - <a href="http://www.highcharts.com/maps/demo">highMaps</a>,  a map library</dd>

                <dt>API</dt>
                <dd> - <a href="https://freegeoip.net">freeGeoIP</a>,  public HTTP API  to search the geolocation of IP addresses</dd>
            </dl>
        </div>
    </div>


    <div class="row" style="margin-top:80px;">
        <div class="  col-xs-12  text-left">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li><a href="#About">About</a></li>
                <li class="active">Content</li>
            </ol>
        </div>

        <div class="  col-xs-12 text-left">
            <dl>
                <dt>Userpics</dt>
                <dd>
                    - <a href="https://en.wikipedia.org/wiki/Al_Hirschfeld">Al Hirschfeld</a> caricatures of celebrities and Broadway stars
                </dd>
            </dl>
        </div>

        <div class="col-xs-9 col-md-7 text-left">
            @Html.Action("GetUsersForSideBar", "User")
        </div>
    </div>

    <div class="row" style="margin-top:50px;">
        <div class="  col-xs-12 text-left">
            <dl>
                <dt>Advertisement</dt>
                <dd>
                    - <a href="https://en.wikipedia.org/wiki/Al_Hirschfeld">Al Hirschfeld</a> vintage posters
                </dd>
            </dl>
        </div>

        <div class="col-xs-12 col-md-6 text-left">
            <img class="img-responsive" src="/Content/posters/poster3.jpg" />
        </div>
    </div>

    <div class="row" style="margin-top:50px; ">
        <div class="  col-xs-12 text-left">
            <dl>
                <dt>Posts</dt>
                <dd>
                    - my family posts ( <a href="http://igornasa.livejournal.com">igornasa</a>,
                    <a href="http://elefant59.livejournal.com">elefant59</a>) published at
            </dl>
        </div>
        <div class="  col-xs-5 col-md-5 text-left">
            <a href="https://en.wikipedia.org/wiki/LiveJournal">
                <img class="img-responsive" style="border:solid 1px lightgray; padding:12px;margin:0px;" src="/Content/Demo/logo22.png" />
            </a>
        </div>
    </div>

}

@section RightSideContent
 {
    <div class="row">
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li><a href="#About">About</a></li>

                <li class="active">Screenshots</li>
            </ol>
        </div>

        <div class=" col-xs-12">
            <p>
                Select posts by category or tag
            </p>
            <img class="img-responsive img-demo" src="/Content/Demo/Demo2.jpg" />
        </div>

        <div class=" col-xs-12 ">
            <p>
                Cropping  userpics
            </p>
            <img class="img-responsive img-demo" src="/Content/Demo/Demo3.jpg" />
        </div>

        <div class=" col-xs-12 ">
            <p>Hierarchy comments</p>
            <img class="img-responsive img-demo" src="/Content/Demo/Demo1.jpg" />
        </div>

        <div class=" col-xs-12 ">
            <p>Manage friends list</p>
            <img class="img-responsive img-demo" src="/Content/Demo/Demo7.jpg" />
        </div>
       
        <div class=" col-xs-12 ">
            <p>Visitors map</p>
            <img class="img-responsive img-demo" src="/Content/Demo/report3.jpg" />
        </div>
        <div class=" col-xs-12 ">
            <p>Received comments chart</p>
            <img class="img-responsive img-demo" src="/Content/Demo/report1.jpg" />
        </div>
    </div>
}

LJ/Views/Home/Contact.cshtml
@{
    Layout = "~/Views/Shared/_LayoutOld.cshtml"; 
}
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LJ/Views/Home/GetTopPosts.cshtml
@model LJ.ViewModels.ViewModelPosts

<div id="content">

    <h1>@ViewBag.Title</h1>

    @Html.Partial("_PostPager", Model)

    @if (Model.TotalPosts > 0)
    {
        foreach (var post in Model.Posts)
        {
            @Html.Partial("_PostTemplate", post)
        }
    }
    else
    {
        <p>No posts found!</p>
    }

    @Html.Partial("_PostPager", Model)

</div>

LJ/Views/Home/Help.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDemo.cshtml";
}

@{
    ViewBag.Title = "Help Page";
}


@section MainContent{

    <div class="row">
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li><a href="#Help">Help</a></li>
                <li class="active">Login as an user</li>
                </ol>
        </div>
    </div>           
    @Html.Action("GetUsersWithLogins", "User")

}

@section RightSideContent{
    <div class="row">
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="#"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li class="active">Advertisement</li>
            </ol>
        </div>
    </div>
    @Html.Partial("_Ad", 3)
}

LJ/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutDemo.cshtml";
}

@{
    ViewBag.Title = "Home Page";
}






@section MainContent{

    <div class="row">
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
                
                <li class="active">Home</li>
                </ol>
        </div>
    </div>
    <div class="jumbotron text-center">

            @Html.Action("GetInfoForFrontPage", "User", new { usercount = 3, postcount =3 })

    </div>
}

LJ/Views/Home/TopPostTemplate.cshtml
@using LJ.Models.Blog;
@model Post

    <div class="post">
        <div class="post-meta">
            <div class="row">
                <div class="post-title"><h2>@Html.PostLink(Model)</h2> </div>
            </div>
            <div class="row">
                <div class="post-category">by @Html.UserNameLink(Model)</div>
                <div class="posted-date">@Model.PostedOn.ToConfigLocalTime()</div>
            </div>
        </div>
        <div class="post-body">@Html.Raw(Model.ShortDescription)</div>
        <div class="post-category"><span>Category: </span>@Html.CategoryLink(Model.Category)</div>
        <div class="post-foot">
            @Html.ActionLink("read more...", "GetPost", "Blog",
        new
        {
            year = Model.PostedOn.Year,
            month = Model.PostedOn.Month,
            day = Model.PostedOn.Day,
            url = Model.Url
        },
        new { title = "continue..." }
    )
        </div>
    </div>