LJ/Models/Blog/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Infrastructure;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;


namespace LJ.Models.Blog
{   [Table ("Categories")]
    public class Category
    {
        public  int Id
        { get; set; }

        [Required(ErrorMessage = "Category Name: Field is required")]
        [StringLength(500, ErrorMessage = "Tag Name: Length should not exceed 500 characters")]
        public  string Name
        { get; set; }

       [Required(ErrorMessage = "Category Url: Field is required")]
        [StringLength(500, ErrorMessage = "Tag Url: Length should not exceed 500 characters")]
        public  string Url
        { get; set; }

        public  string Description
        { get; set; }

        [JsonIgnore]
        [InverseProperty("Category")]
        public virtual ICollection<Post> Posts
        { get; set; }
    }
}

LJ/Models/Blog/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LJ.Models.User;


namespace LJ.Models.Blog
{
    public class Comment
    {
        public int Id { get; set; }

        public int PostId { get; set; }
        [ForeignKey ("PostId")]
        public virtual Post Post { get; set; }
        

        public DateTime DateTime { get; set; }
        public string UserName { get; set; }

        [Required]
        public string Body { get; set; }

        [DefaultValue(0)]
        public int NetLikeCount { get; set; }

        public int StatusId { get; set; }
        [NotMapped]
        public Status StatusValue
        {
            get { return (Status)StatusId; }
            set { StatusId = (int)value; }
        }
       
        public int UserImageId { get; set; }
        public ApplicationUserImage UserImage { get; set; }

        public virtual ICollection<Reply> Replies { get; set; }
        public ICollection<CommentLike> CommentLikes { get; set; }
    }
}

LJ/Models/Blog/CommentLike.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LJ.Models.User;

namespace LJ.Models.Blog
{
    public class CommentLike
    {
        [Key]      
        public int Id { get; set; }

        [ForeignKey("Comment")]
        public int CommentId { get; set; }
        public virtual Comment Comment { get; set; }

        public virtual ApplicationUser User { get; set; }

        public bool Like { get; set; }
        public bool Dislike { get; set; }
    }
}

LJ/Models/Blog/CommentSortOrders.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using LJ.Models.User;

namespace LJ.Models.Blog
{
    public enum CommentSortOrders
    {
        Earliest = 1, 
        Oldest = 2, 
        Best = 4, 
        Worst = 8, 
        Heaviest = 16, 
        Lightest = 32
    }
}

LJ/Models/Blog/DeleteCommenReplyInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using LJ.Models.Blog;

namespace LJ.Models.Blog
{
    public class DeleteCommenReplyInfo
    {
        public int Id { get; set; }
        public bool Deleted { get; set; }
        public string DateTime { get; set; }        
    }

    public class DeleteInfo
    {
        public DeleteInfo()
        {
            ReplyIdsForDelete = new List<DeleteCommenReplyInfo>();
            CommentIdsForDelete = new List<DeleteCommenReplyInfo>();
            DeletedReplyText = "This reply has been deleted";
            DeletedCommentText ="This comment has been deleted";
             
        }
        public IList<DeleteCommenReplyInfo> ReplyIdsForDelete {get; set;}
        public IList<DeleteCommenReplyInfo> CommentIdsForDelete { get; set; }

        public  string DeletedReplyText { get; set; }
        public  string DeletedCommentText { get; set; }
    
    }

}

LJ/Models/Blog/JobType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LJ.Models.Blog
{
    public enum JobType { 
        HingFireJob = 1, 
        CustomJob = 2 
    };
  
}

LJ/Models/Blog/Likes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LJ.Models.Blog
{
    
    public enum Likes
    {
        Post =1,
        Comment = 2,
        Reply = 4,

        Like = 8,
        Dislike = 16,

        LikePost = (8 + 1),
        LikeComment = (8 + 2),
        LikeReply = (8 + 4),

        DislikePost = (16 + 1),
        DislikeComment = (16 + 2),
        DislikeReply = (16 + 4),

        PostCommentReply = (1 + 2 + 4),
        LikeDislike = ( 8 + 16)
    } 
}

LJ/Models/Blog/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using LJ.Models.User;

namespace LJ.Models.Blog
{
    public class Post
    {
        public  int Id
        { get; set; }
         public  int SecurityStatus 
         { get; set; }

        [NotMapped]
        public int CurrentTopOrder { get; set; }
        public int CurrentTopRating { get; set; }

        public string ApplicationUserId // ASP Identity Id
        { get; set; }
        [ForeignKey("ApplicationUserId")]
        public ApplicationUser ApplicationUser 
        { get; set; }

        [Required(ErrorMessage = " is required")]
        [StringLength(200, ErrorMessage = " Length should not exceed 200 characters")]
        public  string Title
        { get; set; }

         [Display(Name = "Short Description")]
        [Required(ErrorMessage = "Short Description: Field is required")]
        public  string ShortDescription
        { get; set; }
       
        public string Content
        { get; set; }

        [Display(Name = "Content")]
        [Required(ErrorMessage = "Content: Field is required")]
        public  string Description
        { get; set; }
      
        public  string Meta
        { get; set; }
      
        public  string Url
        { get; set; }

        public  bool Published
        { get; set; }
      
        public ICollection<Group> Groups { get; set; }

        public  DateTime PostedOn
        { get; set; }

        public  DateTime? Modified
        { get; set; }

        public int UserImageId { get; set; }
        public ApplicationUserImage UserImage { get; set; }

        [Display(Name = "Post category")]
        [Required(ErrorMessage = " is required")]
        public int CategoryId
        { get; set; }

        [ForeignKey("CategoryId")]
        public  Category Category
        { get; set; }
        
        [InverseProperty("Post")]
        public virtual ICollection<PostRating> PostRatings 
        { get; set; }
        
        [InverseProperty("Post")]
        public virtual ICollection<Comment> Comments 
        { get; set; }

        [InverseProperty("Post")]
        public virtual ICollection<Reply> Replies 
        { get; set; }

        [InverseProperty("Post")]
        public virtual ICollection<PostLike> PostLikes 
        { get; set; }

        public virtual ICollection<Tag> Tags
        { get; set; }

         
        
    }
}

LJ/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using System.Globalization;
using System.Threading.Tasks;
using System.Data.Entity;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Drawing2D;
using LJ.ViewModels.User;
using LJ.Models.Blog;
using LJ.Models.User;
using LJ.Models.Visitor;
using System.Net;
using LJ.Repository.UserRepository;
using LJ.Infrastructure;
using LJ.Models.Account;
using LJ.Filters;

namespace LJ.Controllers
{
    [AllowAnonymous]
    public class UserController : Controller
    {

        private IUserRepository<ApplicationUser,int> _repository;
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;


        public UserController(IUserRepository<ApplicationUser, int> repository)
        {
            _repository = repository;
           

        }
        public UserController(IUserRepository<ApplicationUser, int> repository, ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            _repository = repository;
            UserManager = userManager;
            SignInManager = signInManager;

        }

        private async Task<ApplicationUser> GetCurrentUserAsync()
        {
            return await UserManager.FindByIdAsync(User.Identity.GetUserId());
        }


        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }


        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        


        // from http://www.codeproject.com/Articles/379980/Fancy-ASP-NET-MVC-Image-Uploader
        //===========================
        public ActionResult Index(int id)
        {
            return PartialView(id);

        }


        [HttpGet]
        public ActionResult UploadImage()
        {
            return View();
        }



        [HttpPost]
        public ActionResult UploadImage(ImageCropForDisplyViewModel model)
        {
            if (ModelState.IsValid)
            {
                Bitmap original = null;
                var name = "newimagefile";
                var errorField = string.Empty;

                if (model.IsUrl)
                {
                    errorField = "Url";
                    name = GetUrlFileName(model.Url);
                    original = GetImageFromUrl(model.Url);
                }
                else if (model.IsFlickr)
                {
                    errorField = "Flickr";
                    name = GetUrlFileName(model.Flickr);
                    original = GetImageFromUrl(model.Flickr);
                }
                else 
                {
                    errorField = "File";
                    name = Path.GetFileNameWithoutExtension(model.File.FileName);
                    original = Bitmap.FromStream(model.File.InputStream) as Bitmap;
                }

                if (original != null)
                {
                    var img = CreateImage(original, model.X, model.Y, model.Width, model.Height);
                    var imgmodel = new ApplicationUserImage
                        {
                            ImageMimeType = model.File.ContentType,
                            ImageData = ImageToByte(img)
                        };
                    int i =_repository.SaveImage(imgmodel);
                    return RedirectToAction("Index", new { id = i });
                }
                else
                    ModelState.AddModelError(errorField, "Your upload did not seem valid. Please try again using only correct images!");
            }

            return View(model);
        }

        //============================
         [NonAction]
        public static byte[] ImageToByte(Image img)
        {
            ImageConverter converter = new ImageConverter();
            return (byte[])converter.ConvertTo(img, typeof(byte[]));
        }



        //=============================
        [NonAction]
         public string GetUrlFileName(string url)
        {
            var parts = url.Split(new char[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
            var last = parts[parts.Length - 1];
            return Path.GetFileNameWithoutExtension(last);
        }



        //===========================
        [NonAction]
        Bitmap GetImageFromUrl(string url)
        {
            var buffer = 1024;
            Bitmap image = null;

            if (!Uri.IsWellFormedUriString(url, UriKind.Absolute))
                return image;

            using (var ms = new MemoryStream())
            {
                var req = WebRequest.Create(url);

                using (var resp = req.GetResponse())
                {
                    using (var stream = resp.GetResponseStream())
                    {
                        var bytes = new byte[buffer];
                        var n = 0;

                        while ((n = stream.Read(bytes, 0, buffer)) != 0)
                            ms.Write(bytes, 0, n);
                    }
                }

                image = Bitmap.FromStream(ms) as Bitmap;
            }

            return image;
        }



        //===================================
        Bitmap CreateImage(Bitmap original, int x, int y, int width, int height)
        {
            var img = new Bitmap(width, height);

            using (var g = Graphics.FromImage(img))
            {
                g.SmoothingMode = SmoothingMode.AntiAlias;
                g.InterpolationMode = InterpolationMode.HighQualityBicubic;
                g.DrawImage(original, new Rectangle(0, 0, width, height), x, y, width, height, GraphicsUnit.Pixel);
            }

            return img;
        }



        //=====================================
        [AllowAnonymous]
        public FileContentResult GetImage(int id)
        {
            ApplicationUserImage f = _repository.GetImageBy(id);
            if (f == null || f.ImageData == null) return null;
            return File(f.ImageData, f.ImageMimeType);

        }

        // User Profile
        //===========================
        [HttpGet]          
        [VisitorActionFilter(ActionType = (int)ActionType.SeeProfile, UserName = "id")]
        public ActionResult GetProfile(string id)
        {  //id ==username
            var profile = _repository.GetProfileBy(id);
            if (profile == null) return View("Error", "No this blogger");
      
            return View(profile);
        }

        
        //====================================
        [HttpGet]
        [VisitorActionFilter(ActionType = (int)ActionType.EditProfile)]
        public ActionResult EditProfile(string id)
        {
            var username = id;
            UserViewModel user;
            if (username == "") user = new UserViewModel();
            else
            {
                var userFromDb = _repository.GetUserBy(username);
                if (userFromDb == null)
                    return View("Error", "No this blogger");
                else
                    user = new UserViewModel(userFromDb);
            }
            return View(user);
        }


        //==================================================
       [HttpPost]
       [ValidateAntiForgeryToken]
       [ValidateInput(false)]
        public ActionResult SaveSectionUserpics(UserViewModel user, int DefaultIdOrder,
           IEnumerable<ImageViewModel> UserImages, 
           IEnumerable<ImageViewModel> UploadedUserImages)
        {
            string username = user.UserName;
            int result = 1;
            List<ApplicationUserImage> imagesToAdd = new List<ApplicationUserImage>();
            var errorField = string.Empty;
            
            if (ModelState.IsValid)
            {           
                //If have images
                if (user.UserImages != null )
                {
                    // set order number for all images
                    var images = user.UserImages
                        .Select((i, index) => new { OrderId = index + 1, Image = i }).ToList();  
                
                    //if have new images
                    if (user.UploadedUserImages != null) {
                        // set orderid for uploaded images (new) images
                        var newImages = user.UploadedUserImages
                             .Join(images.Where(a => a.Image.Id == 0),
                                           i1 => i1.NewImageId,
                                           i2 => i2.Image.NewImageId,
                                          (i1, i2) => new { OrderId = i2.OrderId, NewImage = i1 }).ToList();

                        //create new Images;
                        foreach (var img in newImages)
                        {
                            Bitmap originalImage = null;
                            var newImage = (UploadedImageViewModel)img.NewImage;
                            var uploadType = newImage.ImageUploadTypeId & (int)ImageUploadType.IsFileFlickrUrl;
                            string contentType;
                         
                            switch (uploadType)
                            {
                                case (int)ImageUploadType.Url:
                                    errorField = "Url";

LJ/Views/Blog/ChildReplies.cshtml
@model IEnumerable<CommentViewModel>

@using LJ.Models;
@using LJ.Controllers;
@using LJ.Infrastructure;
@using System.Globalization;
@using Microsoft.AspNet.Identity;
@using LJ.Repository;
@using LJ.Models.Blog;
@using LJ.ViewModels;
@using System.Web;

@{
 string username = User.Identity.GetUserName();
 string userDefaultImageId = User.Identity.GetIdentityImageId();
 var imgUrl = Url.Action("GetDefaultImage", "Blog", new { username = username }) ?? Url.Content("~/Content/UserImages/NoImage.jpg");
}
@foreach (var reply in Model)
{
    if (reply != null)
    {
        var replyId = reply.Id;
        var replyUserName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(reply.UserName);
        var replyPassedTime = LJ.Infrastructure.Extensions.TimePassed(reply.DateTime); 
        var replyDate = StatusNames.GetStatusName(reply.StatusId) +
                               reply.DateTime.ToLongDateString().Replace(reply.DateTime.DayOfWeek.ToString() +
                                  ", ", "");
        var level = (int)ViewBag.level;
        var marginOffset = (level * 15).ToString() + "px";
        var marginOffsetForNewChildReply = ((level + 1) * 15).ToString() + "px";
        var likes = reply.CommentLikes;
        var dislikes = reply.CommentDislikes;
        var twshareUrl = "https://twitter.com/intent/tweet?text=" + reply.Body + "  -- " + reply.UserName + "&url=" + Url.Encode(HttpContext.Current.Request.Url.AbsoluteUri);

        <div class="row" id="rpreplyid" style="margin-left:@marginOffset;">
            <div class="col div-comment-top">
                <div class="comImg">
                    <div class="userImage comment-top"><img src="/Blog/GetImage/@reply.UserImageId" height="50" width="50" /></div>
                    <div class="commentUserName comment-top">
                        <span class="glyphicon glyphicon-user"></span> <strong>@replyUserName</strong>&nbsp;&nbsp;<span class="cmntTime">-- @replyPassedTime</span><br />
                        @replyDate
                        @if ((reply.StatusId & (int)Status.Deleted) == 0 && reply.UserName == User.Identity.GetUserName())
                        {
                            <br />
                            <a href="Blog/EditReply/@reply.Id" class="btn btn-default btn-xs comment-menu-items edit-comment-reply">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </a>
                            <a href="@Url.Action("DeleteReply", "Blog", new {replyid = reply.Id, username = username })"
                               alt="Delete comment" title="Delete comment" class="btn btn-default btn-xs confirm-delete">
                                <span class="glyphicon glyphicon-remove comment-menu-items" aria-hidden="true"></span>
                            </a>
                        }
                    </div>
                </div>
            </div>
        </div>
    <div class="row" style="margin-left:@marginOffset;">
        <div class="col row-comment-body">
            @Html.Raw(reply.Body)
        </div>
    </div>

        if ((reply.StatusId & (int)Status.Deleted) == 0)
        {
            <div class="row replySubMenu row-bottom-comment-menu" style="margin-left:@marginOffset;">
                <div class="col">
                    <a class="linklike" alt="Like" title="Like @reply.UserName reply"
                       href="@Url.Action("UpdateLikes", "Blog", new { id = reply.Id, username = username, likeordislike = (int)Likes.LikeReply,  sortorder = ViewBag.CurrentSort })">
                        <span class="glyphicon glyphicon-thumbs-up"></span>
                    </a>
                    <a class="likecount" style="color:green;">@likes</a>
                    <a class="linklike" alt="Dislike" title="Dislike @reply.UserName reply"
                       href="@Url.Action("UpdateLikes", "Blog", new { id = reply.Id, username = username, likeordislike = (int)Likes.DislikeReply, sortorder = ViewBag.CurrentSort })">
                        <span class="glyphicon glyphicon-thumbs-down"></span>
                    </a>
                    <a class="likecount" style="color:red;">@dislikes</a>

                    @if (Request.IsAuthenticated)
                    {
                        <a class="btn btn-default  btn-xs comment-menu-items new-comment-reply" href="/Blog/NewChildReply/@reply.Id"><span style="font-size:18px;" class="glyphicon glyphicon-edit"></span></a>
                    }
                </div>
            </div>           
        }
        @Html.Action("ChildReplies", new { parentReplyId = reply.Id, level = level + 1 })
    }
}

LJ/Views/Blog/GetUserImages.cshtml
@model string  
@using LJ.Models.Blog;
@using LJ.Models.User;

@{
    
    var userImageIds = User.Identity.GetIdentityImageIds();
    var userSelectedImageId = Model ;
}
    
@if (userImageIds == null || userImageIds.Count() == 0)
{
    <img height="50" width="50" src="@Url.Content("~/Content/UserImages/NoImage.jpg")" alt="no image" />
}
else if ((userImageIds.Count() == 1))
{
    <img height="50" width="50" src="@Url.Content("/Blog/GetImage?id=" + @userSelectedImageId)" />
}
else
{
    <select id="ddimages">
        @foreach (var img in userImageIds)
        {
            if (userSelectedImageId == img)
            {
                <option value="@img" data-imagesrc="@Url.Content("/Blog/GetImage?id="+img)" selected="selected"></option>
            }
            else
            {
                <option value="@img" data-imagesrc="@Url.Content("/Blog/GetImage?id="+img)"></option>
            }
        }
    </select>
}

LJ/Views/Blog/Index.cshtml
@model IEnumerable<LJ.Models.Blog.Post>
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@foreach (var el in Model)
{
    @el.Id<br />  @el.Title<br />
}

LJ/Views/Blog/PostPaging.cshtml
@model LJ.ViewModels.PostViewModel
@using LJ.Models.User;
@{
    long friendType = Model.UserPanelInfo.FriendType;

    string username = Model.UserPanelInfo.UserName;
    bool isFilter = Model.FilterCategory != null || Model.FilterTag != null;


    var categoryid = Model.FilterCategory == null ? 0 : Model.FilterCategory.Id;
    var tagid = Model.FilterTag == null ? 0 : Model.FilterTag.Id;



    string filterString = (categoryid == 0 ? "" : "By category \"" + Model.FilterCategory.Name + "\" ") +
                               (tagid == 0 ? "" : "By tag \"" + Model.FilterTag.Name + "\" ");


}

<div class="row">
    <div class="  col-xs-12 text-left">
        <ol class="breadcrumb">

            <li><a href="#"><span class="glyphicon glyphicon-user"></span> @Model.UserName</a></li>
            <li><a href="/Blog/GetUserPosts/@Model.UserName">Posts</a></li>


            @if (isFilter)
            {
                <li class="active">
                    @Html.ActionLink(filterString, "GetUserPosts", "Blog",
                       new { id = Model.UserPanelInfo.UserName, categoryid = categoryid, tagid = tagid }, null)
            </li>
            }
            <li class="active">Post</li>
        </ol>
    </div>
</div>


<div class="row" style="margin-bottom:16px;">
    <div class="col-xs-12 text-right ">
        <span class="label label-default label-primary navigation-posts" style=" padding:10px 10px;">Posts <span class="badge">@Model.PostCount</span></span>
    </div>
</div>


        @using (Html.BeginForm("DeletePost", "Blog",
                       new
                       {
                           postid = Model.Id,
                           nextid = Model.NextPostId,
                           previd = Model.PrevPostId,
                           username = Model.UserName
                       },
                           FormMethod.Post))   
        {
            <div class="row" style="margin-bottom:16px;">
                <div class="col-xs-12 text-center">

                    <div class="btn-group">

                        <a class="btn btn-sm btn-primary @Html.Raw(Model.PrevPostId !=0 ? "" : "disabled")"
                           title="Previous post" id="prevpost"
                           href="@Url.Action( "GetUserPost", "Blog" ,
                            new {
                                sortorder = Model.SortOrder,
                                id= Model.FirstPostId })">
                            <span class="glyphicon glyphicon-chevron-left"></span><span class="glyphicon glyphicon-chevron-left"></span>
                        </a>


                        <a class="btn btn-sm btn-primary @Html.Raw(Model.PrevPostId !=0 ? "" : "disabled")"
                           title="Previous post" id="prevpost"
                           href="@Url.Action( "GetUserPost", "Blog" ,
                            new {
                                sortorder = Model.SortOrder,
                                id= Model.PrevPostId })">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>

                        @if ((Model.UserPanelInfo.FriendType & (int)FriendType.MySelf) > 0)
                        {
                            <a href="/Blog/EditPost/@Model.Id" class="btn btn-default btn-sm "
                               title="@Model.UserName, you can edite your post">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </a>

                            <button type="submit" class="btn btn-default btn-sm confirm-delete-post"
                                    alt="Delete post" title="@Model.UserName, you can delete your post">
                                <span class="glyphicon glyphicon-remove comment-menu-items" aria-hidden="true"></span>
                            </button>
                        }

                        

                        <a class="btn btn-sm btn-default "
                           title="Post top ratings" id="prevpost"
                           href="@Url.Action( "GetPostRatings", "User" ,
                            new {

                                id= Model.Id })" target="_blank">
                            <span class="glyphicon glyphicon-stats comment-menu-items" aria-hidden="true"></span>
                        </a>

                        <a class="btn btn-sm btn-primary @Html.Raw(Model.NextPostId != 0 ? "" : "disabled")"
                           title="Next post"
                           href="@Url.Action( "GetUserPost", "Blog" ,
                            new {
                                sortorder = Model.SortOrder,
                                id= Model.NextPostId })">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>


                        <a class="btn btn-sm btn-primary @Html.Raw(Model.NextPostId !=0 ? "" : "disabled")"
                           title="Previous post" id="prevpost"
                           href="@Url.Action( "GetUserPost", "Blog" ,
                            new {
                                sortorder = Model.SortOrder,
                                id= Model.LastPostId })">
                            <span class="glyphicon glyphicon-chevron-right"></span><span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>


                </div>
            </div>
        }