LJ/Models/Visitor/ActionType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LJ.Models.Visitor
{
    public enum ActionType
    {
        Report = 1, Blog= 2, Edit = 4, Profile = 8, See = 128, Log = 256,
        User = 16, Website = 32, Admin = 64, 
        UserReport= 1 + 16,
        WebsiteReport= 1 + 32, 
        AdminReport = 1 + 64,
        ManageProfile = 8 + 4,

        SeeBlog = 2 + 128,
        EditBlog = 2 + 4,

        SeeProfile = 8 + 128,
        EditProfile = 8 + 4,
        SeeWebsite = 8 + 32,
    }
}

LJ/Models/Visitor/ApplicationVisitor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Collections.Concurrent;
using System.Web.Security;
using System.Web.Mvc;
using LJ.Models.Visitor;
using LJ.Models.User;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LJ.Models.Visitor
{
    public class ApplicationVisitor
    {
        [Key]
        [Column(Order = 1)]
        public string SessionId { get; set; }
        [Key]
        [Column(Order = 2)]
        public DateTime SessionStarted { get; set; }
        public DateTime SessionEnded { get; set; }

        public string UserId { get; set; }
        [ForeignKey("UserId")]
        public ApplicationUser User { get; set; }

        public string CountryId { get; set; }
        public string CountryName { get; set; }
        public string Anonymous { get; set; }
        public string IpAddress { get; set; }
        public string UrlReferrer { get; set; }
        public string EnterUrl { get; set; }
        public string UserAgent { get; set; }
    }
}

LJ/Models/Visitor/ArxivVisitor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Collections.Concurrent;
using System.Web.Security;
using System.Web.Mvc;
using LJ.Models.Visitor;
using LJ.Models.User;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LJ.Models.Visitor
{
    public class ArxivVisitor
    {
        [Key] 
        public int Id { get; set; }
        public int VisitorsCount { get; set; }
        public int UsersCount { get; set; }
        public DateTime Date { get; set; }
 
    }
}

LJ/Models/Visitor/ArxiveVisitorLogForAdmin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LJ.Models.Visitor
{
    public class ArxiveVisitorLogForAdmin
    {
          public long    Id {get; set;}
          public DateTime StartDateTime { get; set; }
          public DateTime EndDateTime { get; set; }
          public string  Controller {get; set;}
          public string  Action {get; set;}
          public int     ActionType { get; set; }
          public long    SpentTimeMC {get; set;}
          public long    CountVisits {get; set;}
          public long    CountUsers {get; set;}
          public long    CountAnonymous {get; set;}
          public long    ExitCount {get; set;}
          public long    BounceCount { get; set; }
    }
}

LJ/Models/Visitor/ArxiveVisitorLogForUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LJ.Models.Visitor
{
    public class ArxiveVisitorLogForUser
    {
        public long Id { get; set; }
        public DateTime StartDateTime { get; set; }
        public DateTime EndDateTime { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int PostId { get; set; }
        public string UserName { get; set; }
        public long SpentTimeMC { get; set; }
        public long CountVisits { get; set; }
        public long CountUsers { get; set; }
        public long CountAnonymous { get; set; }
        public long ExitCount { get; set; }
        public long BounceCount { get; set; }
    }
}

LJ/Models/Visitor/GeoLocation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LJ.Models.Visitor
{
    public class GeoLocation
    {
         public string ip {get; set;}
         public string country_code {get; set;}
         public string country_name {get; set;}
         public string region_code {get; set;}
         public string city {get; set;}
         public string zip_code {get; set;}
         public decimal latitude {get; set;}
         public decimal longitude {get; set;}
         public  int metro_code  {get; set;}


        /*Sample  http://freegeoip.net/
          "ip":"192.30.253.113",
          "country_code":"US",
          "country_name":"United States",
          "region_code":"CA","region_name":"California",
          "city":"San Francisco",
          "zip_code":"94107",
          "time_zone":"America/Los_Angeles",
          "latitude":37.7697,
          "longitude":-122.3933,
          "metro_code":807}*/
    }
}

LJ/Models/Visitor/GeoLocationRestService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace LJ.Models.Visitor
{
    public class GeoLocationRestService
    {
        readonly string uri = "http://freegeoip.net/json/";

        public GeoLocation GetGeoLocation(string ip)
        {

            using (WebClient webClient = new WebClient())
            {

                return JsonConvert.DeserializeObject<GeoLocation>(
                        webClient.DownloadString(uri + ip)
                );
            }
        }

        public async Task<GeoLocation> GetGeoLocationAsync(string ip)
        {

            using (HttpClient httpClient = new HttpClient())
            {

                return JsonConvert.DeserializeObject<GeoLocation>(
                       await httpClient.GetStringAsync(uri + ip)
                );
            }
        }
    }
}

LJ/Models/Visitor/VisitorActionLog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace LJ.Models.Visitor
{
    public class VisitorActionLog
    {
        public Int64 Id { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int ActionType { get; set; }
        public string IpAddress { get; set; }
        public DateTime DateTime { get; set; }

        [NotMapped]
        public TimeSpan SpentTime
        {
            get;
            set;
        }

        public long SpentTimeMC
        {
            get
            {
                return SpentTime.Ticks;
            }
            set
            {
                SpentTime = TimeSpan.FromTicks(value);
            }
        }

        public string UserName { get; set; }
        public string VisitorUserName { get; set; }
        public string Anonymous { get; set; }
        public string SessionId { get; set; }
        public int PostId { get; set; }
        public int TagId { get; set; }
        public int CategoryId { get; set; }
    }
}

LJ/ViewModels/Visitor/OnlineVisitorsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LJ.ViewModels.Visitor
{
    public class OnlineVisitorsViewModel
    {
        public IEnumerable<string> UserNames { get; set; }
        public int AnonimousCount { get; set; }
    }
}

LJ/Controllers/VisitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using System.Globalization;
using System.Threading.Tasks;
using System.Data.Entity;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Net;
using LJ.Infrastructure;
using LJ.Models.Account;
using LJ.Models.Visitor;
using LJ.Models.User;
using LJ.Models.Blog;
using LJ.ViewModels.Visitor;
using LJ.Repository.VisitorRepository;
using LJ.Repository.BlogRepository;
using LJ.ViewModels.User;
using LJ.Filters;



namespace LJ.Controllers
{
    [AllowAnonymous]
    public class VisitorController : Controller
    {       
        private IVisitorRepository<ApplicationVisitor,int> _repository;
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;


        public VisitorController(IVisitorRepository<ApplicationVisitor, int> repository)
        {
            _repository = repository;
        }
        public VisitorController(IVisitorRepository<ApplicationVisitor, int> repository, ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            _repository = repository;
            UserManager = userManager;
            SignInManager = signInManager;
        }

        private async Task<ApplicationUser> GetCurrentUserAsync()
        {
            return await UserManager.FindByIdAsync(User.Identity.GetUserId());
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }


        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        
        
       


        //=====================================================      
        public ActionResult WhoIsOnline()
        {
            
                var visitors = OnlineVisitorsContainer.Visitors == null || OnlineVisitorsContainer.Visitors.Count() == 0 ?
                             0 : OnlineVisitorsContainer.Visitors.Count();
                return View(visitors);
            
        }

        
        //==================================================
        [AcceptVerbs(HttpVerbs.Post)]
        [VisitorActionFilter(ActionType = (int)ActionType.WebsiteReport)]
        public JsonResult GetOnlineVisitorsMap()
        { 
            if (OnlineVisitorsContainer.Visitors != null)
            {

                var visitors = OnlineVisitorsContainer.Visitors;
                             
                visitors.Values.Where(v => v.AuthUser == null  || v.AuthUser == "").Count();
                var users = visitors.Values.Where(v => v.AuthUser != null && v.AuthUser != "")
                             .GroupBy(v => v.AuthUser, v => v)
                             .Select(h => new
                             {
                                 username = h.Key,                               
                                 city = h.FirstOrDefault().GeoLocation.city,
                                 country_name = h.FirstOrDefault().GeoLocation.country_name,
                                 lat = h.FirstOrDefault().GeoLocation.latitude,
                                 lon = h.FirstOrDefault().GeoLocation.longitude
                             }).OrderBy(h => h.username);

                var ananimouses = visitors.Values.Where(v => v.AuthUser == null  || v.AuthUser == "")
                                  .Select(h => new {
                                      username = "Anonymous",
                                      city = h.GeoLocation.city,
                                      country_name = h.GeoLocation.country_name,
                                      lat = h.GeoLocation.latitude,
                                      lon = h.GeoLocation.longitude
                                  }).OrderBy(h => h.country_name);
                var result = users.Union(ananimouses);

                var data = result.Select((d, index) => new { 
                    name = index, 
                    lat = d.lat, 
                    lon = d.lon }).ToArray();

                var info = result.Select((d, index) => new { 
                    index = index,
                    city = d.city,
                    country_name = d.country_name, 
                    username = d.username }).ToArray();

                return Json(new
                {
                    data = data,
                    info = info,
                    usersCount = users.Count(),
                    ananimousesCount = ananimouses.Count()  
                }
                    , JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { data = new { } }, JsonRequestBehavior.AllowGet); 
        }

        //====================================================

        public ActionResult WhoIsOnlineByCountries()
        {
            var visitors = OnlineVisitorsContainer.Visitors == null || OnlineVisitorsContainer.Visitors.Count() == 0 ?
                         0 : OnlineVisitorsContainer.Visitors.Count();
            return View(visitors);
        }



        //======================================================= 
        [AcceptVerbs(HttpVerbs.Get)]
        [VisitorActionFilter(ActionType = (int)ActionType.WebsiteReport)]
        public JsonResult GetOnlineVisitorsByCountriesMap()
        {
            if (OnlineVisitorsContainer.Visitors != null)
            {

                var visitors = OnlineVisitorsContainer.Visitors;

                var users = visitors.Values
                             .Select(v => new
                             {
                                 AuthUser = (v.AuthUser != null && v.AuthUser != "") ? v.AuthUser : v.Anonymous,
                                 IsUser = (v.AuthUser != null && v.AuthUser != ""),
                                 country_code = v.GeoLocation.country_code,
                                 country_name = v.GeoLocation.country_name
                             })
                            .GroupBy(k => k.country_code, k => k)
                            .Select(h => new
                            {
                                code = h.Key,
                                name = h.FirstOrDefault().country_name,
                                usercount = h.Where(r => r.IsUser)
                                      .GroupBy(u => u.AuthUser, u => u.AuthUser).Select(k => k.Key).Count(),
                                ananimouscount = h.Where( r => !r.IsUser)
                                      .GroupBy( u => u.AuthUser , u => u.AuthUser).Select(k => k.Key).Count(),
                            });

                var result = users.Select(c => new
                {
                    code = c.code,
                    name = c.name,
                    usercount = c.usercount,
                    ananimouscount = c.ananimouscount,
                    value = c.usercount + c.ananimouscount
                }).ToArray();


                return Json(new { data = result }, JsonRequestBehavior.AllowGet);
               
            }
            return Json(new { data = new {} }, JsonRequestBehavior.AllowGet);
        }


        //=====================================================
        public ActionResult GetVisitsStatistics()
        {
            var date = _repository.GetHistoryVisitorsStartDate();
            return View(date);

        }


        //=====================================================
        [AcceptVerbs(HttpVerbs.Post)]
        [VisitorActionFilter(ActionType = (int)ActionType.WebsiteReport)]
        public JsonResult GetVisitorsForMonthChart(int month = 0, int year = 0)
        {
           
            var date = DateTime.Now;
            month = month == 0 || month > 12 ? date.Month : month;
            year = year == 0 ? date.Year : year;

            var date1 = new DateTime(year, month, 1, 0, 0, 0);
            var date2 = date1.AddMonths(1).AddMilliseconds(-1);

            IEnumerable<PostStatisticsViewModel> visits = _repository.GetVisitsForMonth(date1, date2);
            var days = Enumerable.Range(1, DateTime.DaysInMonth(year, month)).ToList();

            var result = days.GroupJoin(visits,
                                         d => d, v => v.Day,
                                         (d, v) => new 
                                         {
                                             Day = d,
                                             Count1 = v.Count() == 0 ? 0 : v.FirstOrDefault().Count1,
                                             Count2 = v.Count() == 0 ? 0 : v.FirstOrDefault().Count2,
                                             Count3 = v.Count() == 0 ? 0 : v.FirstOrDefault().Count3,
                                         }).OrderBy(d => d.Day).ToList();
                                            
              
            return Json(new { data = new {
                                            visits = result.Select(v => v.Count1).ToArray(),
                                            users = result.Select(v => v.Count2).ToArray(),
                                            ananimuses = result.Select(v => v.Count3).ToArray(),
                                            visitors = result.Select(v => v.Count3 + v.Count2).ToArray(),
                                            days = days.ToArray(),

LJ/Views/Visitor/GetBouncePagesForAdmin.cshtml
@model IEnumerable<VisitorActionsViewModel>
@using LJ.ViewModels.Visitor;
@using LJ.Models.Visitor;


@section Styles
{
    <link rel="stylesheet" href="/content/bootstrap-datetimepicker.min.css" />
}


@{
    Layout = "~/Views/Shared/_LayoutNew.cshtml";
}

@section CurrentPageInfo
{

}


@section MainContent{

    <div class="row">
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="#"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li class="active">Admin statistics by bounce pages</li>

            </ol>
        </div>
    </div>



   
    <div class="row">
        <div class="  col-sm-6 col-xs-12 hidden-xs text-left"><b>Page / Page Type</b></div>
        <div class="  col-sm-2 col-xs-4 text-left"><b>Views</b></div>
        <div class="  col-sm-2 col-xs-4 text-left"><b>Bounce</b></div>
        <div class="  col-sm-2 col-xs-4 text-left">
            <abbr title="The percentage of single-page visits or the number of visits in which people left your website from the same page they entered on.">
                <b>%Bounce</b>
            </abbr>
        </div>

    </div>

    <div class="h-divider" style="margin-bottom:14px;"></div>
@if (Model.Count() == 0)
{
    <div class="row">
        <div class="  col-xs-12 text-left">No bounce pages</div>
    </div>
}
else
{
    foreach (var i in Model)
    {
        var result = (i.Count2 * 100) / i.Count1;
        var actionType = Enum.GetName(typeof(ActionType), i.ActionType);
        var action = actionType== null? "" : string.Concat(actionType.Select(x => Char.IsUpper(x) ? " " + x : x.ToString())).TrimStart(' ');
        <div class="row">
            <div class="  col-xs-12 text-left"><u>@i.Controller/@i.Action</u></div>
            <div class="  col-sm-6  col-xs-12 text-left">@action</div>
            <div class="  col-sm-2 col-xs-4 text-left">@i.Count1</div>
            <div class="  col-sm-2 col-xs-4 text-left">@i.Count2 </div>
            <div class="  col-sm-2 col-xs-4 text-left">@result%</div>
        </div>
        <hr />
    }
}
}


@section RightSideContent{
    <div class="row">
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li class="active">Advertisement</li>
            </ol>
        </div>
    </div>
    @Html.Partial("_Ad", 2)
}


@section Scripts {

}

LJ/Views/Visitor/GetHistoryVisitorsByCountry.cshtml
@model DateTime
@using LJ.Models.Visitor;
@using LJ.ViewModels.Visitor;
@using System.Collections.Concurrent;
@using System.Web.Security;
@using System.Web;

@{
    Layout = "~/Views/Shared/_LayoutNew.cshtml";
   
}
@section Styles
{
    <link rel="stylesheet" href="/content/bootstrap-datetimepicker.min.css" />
}






@section MainContent{ 

<div class="row">
    <div class="  col-xs-12 text-left">
        <ol class="breadcrumb">
             <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
            <li class="active">Visitors</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="  col-xs-6 col-md-4 col-sm-offset-4 text-left">
        <div class="form-group">
            <div class='input-group date' id='datetimepicker1'>
                <input type='text' class="form-control" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div id="containerMap2" class="col-xs-12"></div>    
</div>
<div id="containerMap" ></div>

}
@section RightSideContent{
    <div class="row">
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li class="active">Advertisement</li>
            </ol>
        </div>
    </div>
    @Html.Partial("_Ad", 2)
}




@section Scripts {
 <!-- datetimepicker  https://eonasdan.github.io/bootstrap-datetimepicker/Installing/ -->
<script type="text/javascript" src="/scripts/moment.min.js"></script>
<script type="text/javascript" src="/scripts/bootstrap-datetimepicker.min.js"></script>

<!--  map -->
<script src="https://code.highcharts.com/maps/highmaps.js"></script>
<script src="https://code.highcharts.com/maps/modules/data.js"></script>
<script src="https://code.highcharts.com/maps/modules/exporting.js"></script>
<script src="https://code.highcharts.com/mapdata/custom/world.js"></script>
<!-- Flag sprites service provided by Martijn Lafeber, https://github.com/lafeber/world-flags-sprite/blob/master/LICENSE -->
<link rel="stylesheet" type="text/css" href="https://cloud.github.com/downloads/lafeber/world-flags-sprite/flags32.css" />


<script>

    $(function () {
        $('#datetimepicker1').datetimepicker({
            defaultDate: new Date(),
            format: 'MMMM YYYY',
            maxDate: moment().endOf("month"),
           // minDate: new Date("@Model")
        });

        fnGetStatistics(0, 0);
        

        $("#datetimepicker1").on("dp.change", function (e) {
            fnGetStatistics(e.date.format('M'), e.date.format('YYYY'));
        });
    });

    

    //---------------------------------------
    function fnGetStatistics(month, year) {
       
        
        $.get("@Url.Action("GetHistoryVisitorsMap", "Visitor")",
             { month: month, year: year }, function (result) {
                 var data = result.data;
                 
                 var statisticsDate = moment([parseInt(result.year), parseInt(result.month) - 1]).endOf("month");
                 var statisticsMonthName = statisticsDate.format('MMMM');

                

            // Add lower case codes to the data set for inclusion in the tooltip.pointFormat
            $.each(data, function () {
               
                this.flag = this.code.replace('UK', 'GB').toLowerCase();
            });
            
            // Initiate the chart
            $('#containerMap').highcharts('Map', {

                title: {
                    text: 'Website visitors by countries  in ' + statisticsMonthName
                },

                legend: {
                    title: {
                        text: 'visits',
                        style: {
                            color: (Highcharts.theme && Highcharts.theme.textColor) || 'black'
                        }
                    }
                },

                mapNavigation: {
                    enabled: true,
                    buttonOptions: {
                        verticalAlign: 'top'
                    }
                },

                tooltip: {
                    backgroundColor: 'white',
                    borderWidth: 2,
                    shadow: false,
                    useHTML: true,
                    padding: 3,
                    pointFormat: '<span class="f32"><span class="flag {point.flag}"></span></span> {point.name}<br/>' +                      
                        '<b>Total visits:</b> {point.value}<br/><b>Total visitors:</b> {point.visitors}<br/><b>Authenticated:</b> {point.usercount}<br/><b>Anonimuous:</b> {point.ananimouscount}<br/>',

                    positioner: function () {
                        return { x: 0, y: 250 };
                    }
                },

                colorAxis: {
                    min: 1,
                    max: 1000,
                    type: 'logarithmic'
                },

                series: [{
                    data: data,
                    mapData: Highcharts.maps['custom/world'],
                    joinBy: ['iso-a2', 'code'],
                    name: 'Country Totals',
                    states: {
                        hover: {
                            color: '#BADA55'
                        }
                    }
                }]
            });
            //--------------------------
        });
    }
   
</script>




}

LJ/Views/Visitor/WhoIsOnline.cshtml
@model int
@using LJ.Models.Visitor;
@using LJ.ViewModels.Visitor;
@using System.Collections.Concurrent;
@using System.Web.Security;
@using System.Web;

@{
    Layout = "~/Views/Shared/_LayoutNew.cshtml";
   
}



@section MainContent{ 

<div class="row">
    <div class="  col-xs-12 text-left">
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
            <li class="active">Who is online (under construction)</li>
        </ol>
    </div>
</div>
<div id="container" ></div>
<div class="row">
    <div id="container2" class="col-xs-12"></div>    
</div>
}

@section RightSideContent{
    <div class="row">
        <div class="  col-xs-12 text-left">
            <ol class="breadcrumb">
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-cog"></span></a></li>
                <li class="active">Advertisement</li>
            </ol>
        </div>
    </div>
    @Html.Partial("_Ad", 2)
}




@section Scripts {
<!--  latitude/longitude -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.6/proj4.js"></script>

<!--  map -->

<script src="http://code.highcharts.com/maps/highmaps.js"></script>
<script src="https://code.highcharts.com/maps/modules/exporting.js"></script>

<script src="https://code.highcharts.com/mapdata/custom/world-highres.js"></script>
 <!-- jquery template library -->
<script type="text/javascript" src="http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>







<script>
 //http://freegeoip.net/?q=108.41.229.212
//http://www.highcharts.com/docs/maps/map-collection
   
    $(function () {
       
        var dataInfo;
        $.post("@Url.Action("GetOnlineVisitorsMap", "Visitor")", function (data) {
            dataInfo = data.info;

            
          
        // Initiate the chart
        $('#container').highcharts('Map', {

            title: {
                text: 'Right now active visitors on site'
            },

            mapNavigation: {
                enabled: true
            },

            tooltip: {
                headerFormat: '',
               // pointFormat: '<b>{point.name}</b><br>Lat: {point.lat}, Lon: {point.lon}'
                formatter: fnTooltipFormatter
            },

            series: [{
                // Use the gb-all map with no data as a basemap
                mapData: Highcharts.maps['custom/world-highres'],
                name: 'Basemap',
                borderColor: '#A0A0A0',
                nullColor: 'rgba(200, 200, 200, 0.3)',
                showInLegend: false
            }, {
                name: 'Separators',
                type: 'mapline',
                data: Highcharts.geojson(Highcharts.maps['custom/world-highres'], 'mapline'),
                color: '#707070',
                showInLegend: false,
                enableMouseTracking: false
            }, {
                // Specify points using lat/lon
                type: 'mappoint',
                name: 'visitors',
               // color: Highcharts.getOptions().colors[3],
                "marker": {
                    "fillColor": Highcharts.getOptions().colors[1],
                    "lineColor": Highcharts.getOptions().colors[1],
                    "lineWidth": 1,
                    "radius": 2
                },
                dataLabels: {
                    enabled: true,
                    formatter: fnLabelFormatter
                    //format: '{point.name}'
                },
               
                data: data.data
             
            }]
        });
       
      

        $("#tmpUsersInfo").tmpl(data).appendTo("#container2");
        // pointFormat: '<b>{point.name}</b><br>Lat: {point.lat}, Lon: {point.lon}'
        function fnTooltipFormatter() {

            var info = dataInfo[this.point.name];          
            return "<b>Visitor # " + (parseInt(info.index) + 1) + "</b><br/><b>User Name: </b>" +
                  info.username + "<br/><b>Location: </b>" +
                  info.city + ", " + info.country_name;
            
        }

       
        function fnLabelFormatter() {

            var info = dataInfo[this.point.name];
            return "<b>" +info.city +"</b>";

        }
      
        });

      
        
    });
</script>


<script type="text/html" id="tmpUsersInfo">
    <div class="col-xs-12" style="margin-top:16px;margin-bottom:20px;">
        <b>Visitors Total:</b>
        <br class="visible-xs" />
        Authenticated <span style="background-color: rgb(128, 128, 128);" class="badge">${usersCount}</span>
        <br class="visible-xs"/>
        Anonymous  <span style="background-color: rgb(128, 128, 128);" class="badge">${ananimousesCount}</span>
    </div>
    <hr />
    <div class="col-xs-2"><b>Visitor</b></div>
    <div class="col-xs-4"><b>Name</b></div>
    <div class="col-xs-6"><b>Location</b></div>
    {{each info}}
        <div class="col-xs-2">${parseInt(index) +1 }</div>
        <div class="col-xs-4"> {{if username == "Anonymous"}}${username}{{else}} <a href="/User/GetProfile/${username}">${username}</a>{{/if}}</div>
        <div class="col-xs-6">${city}, ${country_name}</div>
    {{/each}}
</script>

}